name: Build and Push EXE

on:
  push:
    branches:
      - build/prod

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile main.py

      - name: Upload EXE to GitHub Packages
        uses: actions/upload-artifact@v2
        with:
          name: main-exe
          path: dist/main.exe
